### ISSUE TITLE
KeyError: '可變的'

### ISSUE THREAD

**Issue by afq984** [afq984/void-battery#5]
version: ef536d2
```
Traceback (most recent call last):
  File "/srv/main.py", line 132, in pob
    data = export(items, tree)
  File "/srv/pobgen.py", line 247, in export
    items, skills = ItemsSkills(tree['items'] + items['items'])
  File "/srv/pobgen.py", line 217, in ItemsSkills
    pob = item_to_pob(item)
  File "/srv/pobgen.py", line 165, in item_to_pob
    return '\n'.join(i_item_to_pob(item))
  File "/srv/pobgen.py", line 130, in i_item_to_pob
    radius = {'小': 'Small', '中': 'Medium', '大': 'Large'}[prop['values'][0][0]]
KeyError: '可變的'
```

**Comment by afq984** [comment]
Should be fixed by #9
