### ISSUE TITLE
nebuloch.names.CannotTranslateName: '法術回音輔助'

### ISSUE THREAD

**Issue by afq984** [afq984/void-battery#6]
version: ef536d2e7da8b2b4d5157c75d9ce9fcdc37a5190
```
Traceback (most recent call last):
  File "/srv/main.py", line 132, in pob
    data = export(items, tree)
  File "/srv/pobgen.py", line 247, in export
    items, skills = ItemsSkills(tree['items'] + items['items'])
  File "/srv/pobgen.py", line 225, in ItemsSkills
    local_skills, abyss = import_socketed_items(item, slot)
  File "/srv/pobgen.py", line 181, in import_socketed_items
    groups[groupId].append(Gem(socketedItem))
  File "/srv/pobgen.py", line 54, in Gem
    nameSpec = nebuloch.names.translate(item['typeLine']).replace(' Support', '')
  File "/srv/nebuloch/names.py", line 28, in translate
    raise CannotTranslateName(name)
nebuloch.names.CannotTranslateName: '法術回音輔助'
```

**Comment by k205045** [comment]
"法術回音": "Spellslinger",
base.json 中沒有輔助二字導致翻譯問題
"法術回音輔助": "Spellslinger",
修改後可正常導出

**Comment by afq984** [comment]
`SkillGems.dat` 裡面有 `法術回音輔助` 這個字串，所以如果有辦法，我比較希望能夠自動從那個裡面抓出翻譯的對應
