### ISSUE TITLE
CannotTranslateMod with '\n附加的小型天賦給予'

### ISSUE THREAD

**Issue by afq984** [afq984/void-battery#7]
version: ef536d2e7da8b2b4d5157c75d9ce9fcdc37a5190

```
Traceback (most recent call last):
  File "/srv/main.py", line 132, in pob
    data = export(items, tree)
  File "/srv/pobgen.py", line 251, in export
    items, skills = ItemsSkills(tree['items'] + items['items'])
  File "/srv/pobgen.py", line 221, in ItemsSkills
    pob = item_to_pob(item)
  File "/srv/pobgen.py", line 169, in item_to_pob
    return '\n'.join(i_item_to_pob(item))
  File "/srv/pobgen.py", line 153, in i_item_to_pob
    yield tr(mod)
  File "/srv/nebuloch/mods.py", line 207, in __call__
    return translate(mod, self.index, self.passives)
  File "/srv/nebuloch/mods.py", line 283, in translate
    raise CannotTranslateMod(mod) from None
nebuloch.mods.CannotTranslateMod: '斧攻擊增加 12% 擊中和異常狀態傷害\n附加的小型天賦給予：劍攻擊增加 12% 擊中和異常狀態傷害'
```

all variants:

```
'斧攻擊增加 12% 擊中和異常狀態傷害\n附加的小型天賦給予：劍攻擊增加 12% 擊中和異常狀態傷害'
'增加 12% 陷阱傷害\n附加的小型天賦給予：增加 12% 地雷傷害'
```

**Comment by afq984** [comment]
Should be fixed by #13.
Reopen if not.
